import './globals.css'
import { Wrappage } from './wrappage'

export const metadata = {
  title: 'Get Github Repository',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wrappage>{children}</Wrappage>
      </body>
    </html>
  )
}
