import './globals.css'
import { UsernameContextProvider } from './context/username'

export const metadata = {
  title: 'Get Github Repository',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UsernameContextProvider>
          {children}
        </UsernameContextProvider>
      </body>
    </html>
  )
}
